micronaut:
  server:
    cors:
      enabled: true
      configurations:
        all:
          allowedOrigins:
            - http://localhost:3000

akhq:
  connections:
    local:
      properties:
        bootstrap.servers: "localhost:9092"
        security.protocol: SSL
        ssl.truststore.location: ssl-dev/kafka.client.truststore.p12
        ssl.truststore.password: changeit
        ssl.keystore.type: "PKCS12"
        ssl.keystore.location: ssl-dev/kafka.client.keystore.p12
        ssl.keystore.password: changeit
        ssl.endpoint.identification.algorithm: ""