version: '3.6'

volumes:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local
  kafka-data:
    driver: local
  ui-modules:
    driver: local
  ui-build:
    driver: local

services:

  zookeeper:
    image: confluentinc/cp-zookeeper
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data:Z
      - zookeeper-log:/var/lib/zookeeper/log:Z
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_ADMIN_ENABLE_SERVER: 'false'
      HOST_HOSTNAME: dockerhost
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka
    volumes:
      - kafka-data:/var/lib/kafka/data:Z
      - ./ssl-dev:/etc/kafka/secrets
    hostname: kafka-server.ssl.dev
    environment:
      KAFKA_BROKER_ID: '0'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_NUM_PARTITIONS: '12'
      KAFKA_COMPRESSION_TYPE: 'gzip'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      KAFKA_LISTENERS: 'SSL://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'SSL://:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'SSL'
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_JMX_PORT: '9091'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_AUTHORIZER_CLASS_NAME: 'kafka.security.auth.SimpleAclAuthorizer'
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
      HOST_HOSTNAME: kafka-client.ssl.dev
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.server.keystore.p12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: keystore_pw.txt
      KAFKA_SSL_KEY_CREDENTIALS: key_pw.txt
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.p12
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: truststore_pw.txt
      KAFKA_SSL_CLIENT_AUTH: 'required'
    links:
      - zookeeper
    ports:
      - 9092:9092
      - 9091:9091
